# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJLXDf4-2CHKprB3auvkjNvYWnrLExFf
"""


import subprocess
import time
import ast

from os import name

from openai import OpenAI
import wikipedia




wikipedia.set_rate_limiting(True)

def Search(query:str):
    try:
        wikipedia.set_user_agent("finetuneLLM/1.0 (contact@example.com)")
        page = wikipedia.search(query,results=10)
        if  page:
            return page
        return None
    except Exception as e :
        print(f"Search Function error type: {type(e).__name__}, details: {e}")
        return None







def Calculator(A:int | float,B:int | float, operator :str):
    match operator:
        case 'add':
            return A+B
        case 'divide' :

            return A/B
        case 'multiply':
            return A*B
        case 'subtraction':
            return A-B
        case _ :
            return 'Invalid operator'


def Search_page(query):
  try :
        wikipedia.set_user_agent("finetuneLLM/1.0 (contact@example.com)")
        page = wikipedia.summary(query,auto_suggest=False)
        if page :
            return page
        return None

  except Exception as e :
      print('error occured at search page ' , e )
      return None

userinput='what is ur name ? '

client =OpenAI(
    base_url='http://localhost:11434/v1/',
    api_key='ollama'
)
answer = client.responses.create(
    model="qwen2.5:7b",
    input=[
    {
        "role": "system",
        "content": """
You are a ReAct agent.

You have access to Search and Calculator tools.

Rules:
1. Use Search whenever the user asks for current, recent, updated,
   live, or time-sensitive information.
2. Use Calculator for mathematical calculations.
3. Do not answer from your own knowledge when Search is required.
4. After receiving a tool result, analyze it and determine whether
   another tool call is necessary.
5. Only provide the final answer when you have enough information.
6. the Search will return summaries analyze them to answer the user Do not mention that u have context just answer naturally
7. If the user asks multiple questions, answer ALL of them.
After calling multiple tools, use ALL tool results in the final answer.
Never ignore a completed tool call.
8- REQUIRED  answer naturally do not mention receiving any information
"""
    },
    {
        "role": "user",
        "content": f"{userinput}"
    }
],
    tools=cast(any,[
        {
            "name": "Search",
            "type": "function",
            "description": "This function is used when Updated information Needed IT will return Summaries From Wikipedia analyze  them to answer the users Question",
            "parameters":{
                "type":"object",
                "properties":{
                    "query":{
                    "type":"string"
                    ,"description":"the search query"
                }}
            }
            ,"required":['query']
        },
        {
            "name": "Calculator",
            "type": "function",
            "description": "Perform basic math calculations.",
            "parameters": {
                "type": "object",
                "properties": {
                    "operation": {
                        "type": "string",
                        "enum": ["add", "subtract", "multiply", "divide"],
                        "description": "The math operation to use.",
                    },
                    "numbers": {
                        "type": "array",
                        "items": {"type": "number"},
                        "description": (
                            "The two numbers to calculate, e.g. [8, 8]"
                        ),
                    },
                },
                "required": ["operation", "numbers"],
            },
        },
    ])
)

import json
print(answer.id)

while True :


  theoutput=[]
  if not answer.output:
    print('the answer is empty ')
    break
  for output in answer.output :
    print(output.type)

    if output.type !=  'function_call':
      continue
    match output.name :
        case 'Search':
          asn = output.arguments
          query = json.loads(asn)
          query = query['query']
          print(query)
          res = Search(query)

          summary_strings=[]
          for result in res :
            summary = Search_page(result)
            if summary is not None:
              summary_strings.append(f'query is : {result} and summary is {summary}')
          if summary_strings :
            summary_strings= ','.join(summary_strings)

            theoutput.append( { "type": "function_call_output","call_id":output.call_id ,"output": summary_strings})


        case 'Calculator':
          arg = json.loads(output.arguments)
          A,B = arg['numbers']
          operation =arg['operation']
          result = Calculator(A,B,operation)
          theoutput.append({"type": "function_call_output","call_id":output.call_id,"output": str(result)})
          print('Calculator search id ', output.call_id)


  if not theoutput:
    print(answer.output_text)
    break
  answer = client.responses.create(
        model= "qwen2.5:7b",
        previous_response_id=answer.id   ,
        input =  f"""
Original user question:
{userinput}

Tool results:
{theoutput}

Now answer ALL parts of the original user question.
"""

    )
