# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gj5-ibUNUebFb46Du03pxt0YJu645pJF
"""

!pip install -U transformers

from  peft  import LoraConfig , TaskType

peft_config = LoraConfig(target_modules=["q_proj"], task_type=TaskType.CAUSAL_LM, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1)

from transformers import AutoModelForCausalLM

from huggingface_hub import login
login()

from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map="auto"
)

print("Model loaded successfully without waiting!")

!pip install --upgrade torchao

from peft import get_peft_model

peft_model = get_peft_model(model, peft_config)
peft_model.print_trainable_parameters()

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="lynix",
    learning_rate=1e-3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    num_train_epochs=2,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,
)

from datasets import load_dataset
from transformers import DataCollatorForLanguageModeling

dataset = load_dataset("databricks/databricks-dolly-15k", split="train[:1000]")
dataset = dataset.train_test_split(test_size=0.1)

train_data = dataset['train']
test_data = dataset['test']
print(f"Train rows: {len(train_data)}, Test rows: {len(test_data)}")



!pip install trl

from trl import SFTTrainer

def format_row(sample):
    return {
        "text": f"### Instruction:\n{sample['instruction']}\n\n### Response:\n{sample['response']}"
    }

dataset = dataset.map(format_row)

trainer = SFTTrainer(
    model=peft_model,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    args=training_args,
)

# 3. Train without errors!
trainer.train()
