# -*- coding: utf-8 -*-
"""Langraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pw8gPizOsyBIh3O9tTL83OwlqBnnoua9
"""

!pip install langgraph
!pip install langchain
!pip install langchain-ollama
!pip install wikipedia

!pip install supabase

!sudo apt-get update -qq
!sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
import time
import subprocess
import time
import ast
from os import name
import os
from openai import OpenAI
import wikipedia
import dotenv
from supabase import create_client, Client
import json


from google.colab import userdata

key= userdata.get('Supabase_Key')
url= userdata.get('supabase_url')
supabase_client= create_client(url,key)


subprocess.Popen(
    ["ollama", "serve"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(3)

!ollama pull qwen2.5:7b

from langchain.tools import tool
from langchain_ollama import ChatOllama

model = ChatOllama(
    model='qwen2.5:7b',
    base_url='http://localhost:11434',
)

from langchain.tools import tool
import wikipedia

# Assuming supabase_client is defined and initialized in your environment

@tool
def execute_supabase(query: str) -> str:
    """Executes a safe Supabase client query via dynamic evaluation, blocking destructive operations.

    Args:
        query: A Python expression string interacting with supabase_client (e.g., supabase_client.table("users").select("*").execute())
    """
    try:
        safe_globals = {
            "__builtins__": {},
            "supabase_client": supabase_client
        }
        qrlower = query.lower()
        if "delete" in qrlower or "drop" in qrlower or "truncate" in qrlower:
            return 'Cannot execute that code'

        return eval(query, safe_globals)
    except Exception as e:
        print('Error occured , Details : ', e)
        return e

@tool
def Search(query: str) -> list | None:
    """Queries Wikipedia and returns a list of up to 5 matching page titles.

    Args:
        query: The search term or keywords to look up
    """
    try:
        wikipedia.set_user_agent("finetuneLLM/1.0 (contact@example.com)")
        page = wikipedia.search(query, results=5)
        if page:
            return page
        return None
    except Exception as e:
        print(f"Search Function error type: {type(e).__name__}, details: {e}")
        return None

@tool
def Calculator(A: int | float, B: int | float, operator: str) -> int | float | str:
    """Performs basic arithmetic calculations between two numbers.

    Args:
        A: The first numeric operand
        B: The second numeric operand
        operator: The operation type ('add', 'divide', 'multiply', 'subtraction')
    """
    match operator:
        case 'add':
            return A + B
        case 'divide':
            return A / B
        case 'multiply':
            return A * B
        case 'subtraction':
            return A - B
        case _:
            return 'Invalid operator'


def Search_page(query: str) -> str | None:
    """Retrieves a 5-sentence summary of a specific Wikipedia page without auto-suggestion.

    Args:
        query: The exact title of the Wikipedia page
    """
    try:
        wikipedia.set_user_agent("finetuneLLM/1.0 (contact@example.com)")
        page = wikipedia.summary(query, auto_suggest=False, sentences=5)
        if page:
            return page
        return None
    except Exception as e:
        print('error occured at search page ', e)
        return None

@tool
def get_schema(table_name: str):
    """Fetches the column structure and schema details for a specified Supabase table via a database RPC call.

    Args:
        table_name: The name of the target database table
    """
    try:
        return supabase_client.rpc(
            "get_table_schema",
            {"table_name": table_name}
        ).execute()
    except Exception as e:
        return e

@tool
def get_tables():
    """Retrieves a list of all available tables in the connected Supabase database using a remote procedure call."""
    try:
        return supabase_client.rpc("get_all_database_tables").execute()
    except Exception as e:
        return e

tools = [get_schema, get_tables,execute_supabase,Search,Calculator]
tools_name={tool.name : tool for tool in tools}
model_with_tools = model.bind_tools(tools)

from langchain.messages import AnyMessage
from typing import TypedDict, Annotated
import operator


class MessagesState(TypedDict):
  messages : Annotated[list[AnyMessage],operator]
  llm_calls: int

instructions =  """
 You are a ReAct agent.

Use the provided tools to solve the user's request.
Follow the rules to solve the users request

RULES:

- If the user asks about Supabase data, use the database tools.
- The user must provide the table name.
- Always call get_schema first for a database question.
- If get_schema says the table does not exist, ask the user for a valid table name.
- If the table exists, use execute_supabase to retrieve the requested data.
- Never invent tools.
- Never write code pretending to call a tool.
- Never write SQL.
- When you need a tool, emit an actual function call.
- Do not describe the function call in text.
- Only give a final answer when the question is solved.
-If a Supabase query returns an error, DO NOT repeat the same query.
  Change the query based on the error.
-CRITICALL a Supabase Query must be in this format : execute_supabase(
  "supabase_client.table('Products').select('*', count='exact').execute()"
)

CRITICAL : Follow this Supabase Syntax :
 execute_supabase(
  "supabase_client.table('Products').select('*', count='exact').execute()"
)

 execute_supabase(
  "supabase_client.table('Products').select('name, price').execute()"
 TOOL SELECTION:
- Arithmetic questions ("add", "multiply", etc.) → use Calculator ONLY.
- Wikipedia/lookup questions → use Search.
- Only use get_schema / get_tables / execute_supabase if the user explicitly mentions a table, database, or Supabase.
- Do NOT use database tools for anything else, even if you are unsure how to answer.
"""

from langchain.messages import SystemMessage


def llm_calls(state:dict):
  return {
      'messages':[
          model_with_tools.invoke(
              [
                  SystemMessage(
                      content=instructions
                  )
              ]
              + state['messages']
          )
      ],
      "llm_calls": state.get('llm_calls', 0) + 1
  }

from langchain.messages import ToolMessage


def tool_node(state:dict):
    result = []
    for tool_call in state["messages"][-1].tool_calls:
        tool = tools_name[tool_call["name"]]
        observation = tool.invoke(tool_call["args"])
        result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
    return {"messages": result}

from typing import Literal
from langgraph.graph import StateGraph, START, END


def should_continue(state: MessagesState) -> Literal["tool_node", END]:
  messages = state['messages']
  last_message = messages[-1]
  if last_message.tool_calls:
    return 'tool_node'
  return END

agent_builder = StateGraph(MessagesState)

agent_builder.add_node('llm_calls' , llm_calls)
agent_builder.add_node('tool_node', tool_node)
agent_builder.add_edge(START, 'llm_calls')

agent_builder.add_conditional_edges(
    "llm_calls",
    should_continue,
    ['tool_node', END]
)
agent_builder.add_edge('tool_node', 'llm_calls')
agent = agent_builder.compile()

from IPython.display import Image, display
display(Image(agent.get_graph(xray=True).draw_mermaid_png()))

# Invoke
from langchain.messages import HumanMessage
messages = [HumanMessage(content="Add 3 and 4.")]
messages = agent.invoke({"messages": messages})
for m in messages["messages"]:
    m.pretty_print()